/**
 * 🗄️ PRISMA SCHEMA GENERATOR
 * Auto-generates complete Prisma schema with all models and relations
 */

export function generatePrismaSchema(models: string[]): string {
  return `// 🎯 Auto-generated by setup-warta-gereja
// Do not edit manually - regenerate using npm run setup:warta-gereja

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

// ============================================
// 👤 USER & AUTHENTICATION
// ============================================

model User {
  id            String    @id @default(cuid())
  name          String
  email         String    @unique
  emailVerified DateTime?
  password      String?
  image         String?
  role          UserRole  @default(JEMAAT)
  
  // Relations
  accounts      Account[]
  sessions      Session[]
  member        Member?
  
  // Audit
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  
  @@map("users")
}

enum UserRole {
  ADMIN
  JEMAAT
}

model Account {
  id                String  @id @default(cuid())
  userId            String
  type              String
  provider          String
  providerAccountId String
  refresh_token     String?
  access_token      String?
  expires_at        Int?
  token_type        String?
  scope             String?
  id_token          String?
  session_state     String?

  user User @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@unique([provider, providerAccountId])
  @@map("accounts")
}

model Session {
  id           String   @id @default(cuid())
  sessionToken String   @unique
  userId       String
  expires      DateTime
  user         User     @relation(fields: [userId], references: [id], onDelete: Cascade)

  @@map("sessions")
}

model VerificationToken {
  identifier String
  token      String   @unique
  expires    DateTime

  @@unique([identifier, token])
  @@map("verification_tokens")
}

// ============================================
// 👨‍👩‍👧‍👦 FAMILY
// ============================================

model Family {
  id           String    @id @default(cuid())
  familyHead   String    // Kepala Keluarga
  address      String?
  phone        String?
  totalMember  Int       @default(0)
  
  // Relations
  members      Member[]
  
  // Audit
  createdAt    DateTime  @default(now())
  updatedAt    DateTime  @updatedAt
  deletedAt    DateTime?
  createdBy    String?
  updatedBy    String?
  deletedBy    String?
  
  @@map("families")
}

// ============================================
// ⛪ CHURCH GROUP
// ============================================

model ChurchGroup {
  id          String              @id @default(cuid())
  name        String              // PELNAP, PELRAP, PELWAP, PELPRIP, PELPAP
  description String?
  
  // Relations
  members     MemberChurchGroup[]
  
  // Audit
  createdAt   DateTime            @default(now())
  updatedAt   DateTime            @updatedAt
  deletedAt   DateTime?
  createdBy   String?
  updatedBy   String?
  deletedBy   String?
  
  @@map("church_groups")
}

// ============================================
// 👥 MEMBER (JEMAAT)
// ============================================

model Member {
  id              String              @id @default(cuid())
  userId          String?             @unique
  familyId        String?
  
  // Personal Info
  nik             String              @unique // NIK KTP
  kk              String?             // Nomor KK
  fullName        String
  gender          Gender
  birthPlace      String?
  birthDate       DateTime?
  phone           String?
  email           String?
  address         String?
  
  // Church Info
  maritalStatus   MaritalStatus       @default(SINGLE)
  hasBaptism      Boolean             @default(false)
  
  // Relations
  user            User?               @relation(fields: [userId], references: [id], onDelete: SetNull)
  family          Family?             @relation(fields: [familyId], references: [id], onDelete: SetNull)
  churchGroups    MemberChurchGroup[]
  baptism         Baptism?
  
  // Audit
  createdAt       DateTime            @default(now())
  updatedAt       DateTime            @updatedAt
  deletedAt       DateTime?
  createdBy       String?
  updatedBy       String?
  deletedBy       String?
  
  @@map("members")
}

enum Gender {
  MALE
  FEMALE
}

enum MaritalStatus {
  SINGLE
  MARRIED
  DIVORCED
  WIDOWED
}

// ============================================
// 🔗 MEMBER - CHURCH GROUP (PIVOT)
// ============================================

model MemberChurchGroup {
  id            String       @id @default(cuid())
  memberId      String
  churchGroupId String
  joinedAt      DateTime     @default(now())
  
  // Relations
  member        Member       @relation(fields: [memberId], references: [id], onDelete: Cascade)
  churchGroup   ChurchGroup  @relation(fields: [churchGroupId], references: [id], onDelete: Cascade)
  
  @@unique([memberId, churchGroupId])
  @@map("member_church_group")
}

// ============================================
// 💧 BAPTISM
// ============================================

model Baptism {
  id            String    @id @default(cuid())
  memberId      String    @unique
  baptismDate   DateTime
  baptismPlace  String?
  minister      String?   // Pendeta yang membaptis
  certificate   String?   // Nomor sertifikat
  
  // Relations
  member        Member    @relation(fields: [memberId], references: [id], onDelete: Cascade)
  
  // Audit
  createdAt     DateTime  @default(now())
  updatedAt     DateTime  @updatedAt
  deletedAt     DateTime?
  createdBy     String?
  updatedBy     String?
  deletedBy     String?
  
  @@map("baptisms")
}

// ============================================
// 📰 POST (WARTA JEMAAT)
// ============================================

model Post {
  id           String         @id @default(cuid())
  title        String
  slug         String         @unique
  content      String
  cover        String?
  publishedAt  DateTime?
  isActive     Boolean        @default(true)
  
  // Relations
  categories   PostCategory[]
  
  // Audit
  createdAt    DateTime       @default(now())
  updatedAt    DateTime       @updatedAt
  deletedAt    DateTime?
  createdBy    String?
  updatedBy    String?
  deletedBy    String?
  
  @@map("posts")
}

// ============================================
// 🏷️ CATEGORY
// ============================================

model Category {
  id        String         @id @default(cuid())
  title     String         @unique
  slug      String         @unique
  
  // Relations
  posts     PostCategory[]
  
  // Audit
  createdAt DateTime       @default(now())
  updatedAt DateTime       @updatedAt
  deletedAt DateTime?
  createdBy String?
  updatedBy String?
  deletedBy String?
  
  @@map("categories")
}

// ============================================
// 🔗 POST - CATEGORY (PIVOT)
// ============================================

model PostCategory {
  id         String   @id @default(cuid())
  postId     String
  categoryId String
  
  // Relations
  post       Post     @relation(fields: [postId], references: [id], onDelete: Cascade)
  category   Category @relation(fields: [categoryId], references: [id], onDelete: Cascade)
  
  @@unique([postId, categoryId])
  @@map("post_category")
}
`;
}
